import { botCommands } from './botCommands';
import { builderData } from './builderData';

export const botTemplates = [
  {
    type: 'template',
    title: 'Бот автоответчик',
    description:
      'Бот ответит стандартным сообщением на запрос от человека. Подходит для всех мессенджеров. Шаблон возможно изменить под ваши цели.',
    icon: 'answering machine',
    messengers: [],
    profile: null,
    features: builderData,
    settings: {},
    commands: botCommands,
    isToPublish: true,
  },
  {
    type: 'template',
    title: 'Доставка еды',
    description: 'Бот поможет оформить заказ в ресторане',
    icon: 'food delivery',
    messengers: [],
    profile: null,
    features: builderData,
    settings: {},
    commands: botCommands,
    isToPublish: true,
  },
  {
    type: 'template',
    title: 'Демо бот',
    description: 'Бот для показа демо',
    icon: 'demo bot',
    messengers: [],
    profile: null,
    features: builderData,
    settings: {},
    commands: botCommands,
    isToPublish: true,
  },
  {
    type: 'template',
    title: 'Опрос',
    description: 'Бот для проведения опросов',
    icon: 'poll',
    messengers: [],
    profile: null,
    features: builderData,
    settings: {},
    commands: botCommands,
    isToPublish: true,
  },
  {
    type: 'template',
    title: 'Лидогенерация/HR ререререре...',
    description: 'Бот для генерации лидов и HR задач',
    icon: 'lead generation',
    messengers: [],
    profile: null,
    features: builderData,
    settings: {},
    commands: botCommands,
    isToPublish: true,
  },
  {
    type: 'template',
    title: 'Онлайн школа/Вебинар',
    description: 'Бот для организации онлайн-школы или вебинаров',
    icon: 'e-learning',
    messengers: [],
    profile: null,
    features: builderData,
    settings: {},
    commands: botCommands,
    isToPublish: true,
  },
  {
    type: 'template',
    title: 'Закрытый клуб по под...',
    description: 'Бот для управления закрытым клубом',
    icon: 'private club',
    messengers: [],
    profile: null,
    features: builderData,
    settings: {},
    commands: botCommands,
    isToPublish: true,
  },
  {
    type: 'template',
    title: 'Агентство по недвижимости',
    description: 'Бот для работы в агентстве по недвижимости',
    icon: 'real estate',
    messengers: [],
    profile: null,
    features: builderData,
    settings: {},
    commands: botCommands,
    isToPublish: true,
  },
  {
    type: 'template',
    title: 'Развлечения',
    description: 'Бот для организации развлечений',
    icon: 'entertainment',
    messengers: [],
    profile: null,
    features: builderData,
    settings: {},
    commands: botCommands,
    isToPublish: true,
  },
  {
    type: 'template',
    title: 'Салон красоты',
    description: 'Бот для управления записями в салоне красоты',
    icon: 'beauty',
    messengers: [],
    profile: null,
    features: builderData,
    settings: {},
    commands: botCommands,
    isToPublish: true,
  },
  {
    type: 'template',
    title: 'Онлайн-покупки',
    description: 'Бот для управления онлайн-магазином',
    icon: 'e-commerce',
    messengers: [],
    profile: null,
    features: builderData,
    settings: {},
    commands: botCommands,
    isToPublish: true,
  },
  {
    type: 'template',
    title: 'Вопрос/ответ',
    description: 'Бот для автоматического ответа на часто задаваемые вопросы',
    icon: 'question',
    messengers: [],
    profile: null,
    features: builderData,
    settings: {},
    commands: botCommands,
    isToPublish: true,
  },
];
